/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/testing"

	rbdv1 "github.com/ceph/ceph-csi/api/rbd/v1"
)

// FakeRBDBackups implements RBDBackupInterface
type FakeRBDBackups struct {
	Fake *FakeRbdV1
	ns   string
}

var rbdbackupsResource = schema.GroupVersionResource{Group: "rbd", Version: "v1", Resource: "rbdbackups"}

var rbdbackupsKind = schema.GroupVersionKind{Group: "rbd", Version: "v1", Kind: "RBDBackup"}

// Get takes name of the rBDBackup, and returns the corresponding rBDBackup object, and an error if there is any.
func (c *FakeRBDBackups) Get(ctx context.Context, name string, options v1.GetOptions) (result *rbdv1.RBDBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(rbdbackupsResource, c.ns, name), &rbdv1.RBDBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*rbdv1.RBDBackup), err
}

// List takes label and field selectors, and returns the list of RBDBackups that match those selectors.
func (c *FakeRBDBackups) List(ctx context.Context, opts v1.ListOptions) (result *rbdv1.RBDBackupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(rbdbackupsResource, rbdbackupsKind, c.ns, opts), &rbdv1.RBDBackupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &rbdv1.RBDBackupList{ListMeta: obj.(*rbdv1.RBDBackupList).ListMeta}
	for _, item := range obj.(*rbdv1.RBDBackupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested rBDBackups.
func (c *FakeRBDBackups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(rbdbackupsResource, c.ns, opts))

}

// Create takes the representation of a rBDBackup and creates it.  Returns the server's representation of the rBDBackup, and an error, if there is any.
func (c *FakeRBDBackups) Create(ctx context.Context, rBDBackup *rbdv1.RBDBackup, opts v1.CreateOptions) (result *rbdv1.RBDBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(rbdbackupsResource, c.ns, rBDBackup), &rbdv1.RBDBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*rbdv1.RBDBackup), err
}

// Update takes the representation of a rBDBackup and updates it. Returns the server's representation of the rBDBackup, and an error, if there is any.
func (c *FakeRBDBackups) Update(ctx context.Context, rBDBackup *rbdv1.RBDBackup, opts v1.UpdateOptions) (result *rbdv1.RBDBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(rbdbackupsResource, c.ns, rBDBackup), &rbdv1.RBDBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*rbdv1.RBDBackup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRBDBackups) UpdateStatus(ctx context.Context, rBDBackup *rbdv1.RBDBackup, opts v1.UpdateOptions) (*rbdv1.RBDBackup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(rbdbackupsResource, "status", c.ns, rBDBackup), &rbdv1.RBDBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*rbdv1.RBDBackup), err
}

// Delete takes name of the rBDBackup and deletes it. Returns an error if one occurs.
func (c *FakeRBDBackups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(rbdbackupsResource, c.ns, name), &rbdv1.RBDBackup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRBDBackups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(rbdbackupsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &rbdv1.RBDBackupList{})
	return err
}

// Patch applies the patch and returns the patched rBDBackup.
func (c *FakeRBDBackups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *rbdv1.RBDBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(rbdbackupsResource, c.ns, name, pt, data, subresources...), &rbdv1.RBDBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*rbdv1.RBDBackup), err
}
