/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/testing"

	rbdv1 "github.com/ceph/ceph-csi/api/rbd/v1"
)

// FakeRBDRestores implements RBDRestoreInterface
type FakeRBDRestores struct {
	Fake *FakeRbdV1
	ns   string
}

var rbdrestoresResource = schema.GroupVersionResource{Group: "rbd", Version: "v1", Resource: "rbdrestores"}

var rbdrestoresKind = schema.GroupVersionKind{Group: "rbd", Version: "v1", Kind: "RBDRestore"}

// Get takes name of the rBDRestore, and returns the corresponding rBDRestore object, and an error if there is any.
func (c *FakeRBDRestores) Get(ctx context.Context, name string, options v1.GetOptions) (result *rbdv1.RBDRestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(rbdrestoresResource, c.ns, name), &rbdv1.RBDRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*rbdv1.RBDRestore), err
}

// List takes label and field selectors, and returns the list of RBDRestores that match those selectors.
func (c *FakeRBDRestores) List(ctx context.Context, opts v1.ListOptions) (result *rbdv1.RBDRestoreList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(rbdrestoresResource, rbdrestoresKind, c.ns, opts), &rbdv1.RBDRestoreList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &rbdv1.RBDRestoreList{ListMeta: obj.(*rbdv1.RBDRestoreList).ListMeta}
	for _, item := range obj.(*rbdv1.RBDRestoreList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested rBDRestores.
func (c *FakeRBDRestores) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(rbdrestoresResource, c.ns, opts))

}

// Create takes the representation of a rBDRestore and creates it.  Returns the server's representation of the rBDRestore, and an error, if there is any.
func (c *FakeRBDRestores) Create(ctx context.Context, rBDRestore *rbdv1.RBDRestore, opts v1.CreateOptions) (result *rbdv1.RBDRestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(rbdrestoresResource, c.ns, rBDRestore), &rbdv1.RBDRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*rbdv1.RBDRestore), err
}

// Update takes the representation of a rBDRestore and updates it. Returns the server's representation of the rBDRestore, and an error, if there is any.
func (c *FakeRBDRestores) Update(ctx context.Context, rBDRestore *rbdv1.RBDRestore, opts v1.UpdateOptions) (result *rbdv1.RBDRestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(rbdrestoresResource, c.ns, rBDRestore), &rbdv1.RBDRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*rbdv1.RBDRestore), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRBDRestores) UpdateStatus(ctx context.Context, rBDRestore *rbdv1.RBDRestore, opts v1.UpdateOptions) (*rbdv1.RBDRestore, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(rbdrestoresResource, "status", c.ns, rBDRestore), &rbdv1.RBDRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*rbdv1.RBDRestore), err
}

// Delete takes name of the rBDRestore and deletes it. Returns an error if one occurs.
func (c *FakeRBDRestores) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(rbdrestoresResource, c.ns, name), &rbdv1.RBDRestore{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRBDRestores) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(rbdrestoresResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &rbdv1.RBDRestoreList{})
	return err
}

// Patch applies the patch and returns the patched rBDRestore.
func (c *FakeRBDRestores) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *rbdv1.RBDRestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(rbdrestoresResource, c.ns, name, pt, data, subresources...), &rbdv1.RBDRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*rbdv1.RBDRestore), err
}
