/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/ceph/ceph-csi/api/rbd/v1"
	scheme "github.com/ceph/ceph-csi/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RBDBackupsGetter has a method to return a RBDBackupInterface.
// A group's client should implement this interface.
type RBDBackupsGetter interface {
	RBDBackups(namespace string) RBDBackupInterface
}

// RBDBackupInterface has methods to work with RBDBackup resources.
type RBDBackupInterface interface {
	Create(ctx context.Context, rBDBackup *v1.RBDBackup, opts metav1.CreateOptions) (*v1.RBDBackup, error)
	Update(ctx context.Context, rBDBackup *v1.RBDBackup, opts metav1.UpdateOptions) (*v1.RBDBackup, error)
	UpdateStatus(ctx context.Context, rBDBackup *v1.RBDBackup, opts metav1.UpdateOptions) (*v1.RBDBackup, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.RBDBackup, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.RBDBackupList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.RBDBackup, err error)
	RBDBackupExpansion
}

// rBDBackups implements RBDBackupInterface
type rBDBackups struct {
	client rest.Interface
	ns     string
}

// newRBDBackups returns a RBDBackups
func newRBDBackups(c *RbdV1Client, namespace string) *rBDBackups {
	return &rBDBackups{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the rBDBackup, and returns the corresponding rBDBackup object, and an error if there is any.
func (c *rBDBackups) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.RBDBackup, err error) {
	result = &v1.RBDBackup{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rbdbackups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RBDBackups that match those selectors.
func (c *rBDBackups) List(ctx context.Context, opts metav1.ListOptions) (result *v1.RBDBackupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.RBDBackupList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rbdbackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested rBDBackups.
func (c *rBDBackups) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("rbdbackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a rBDBackup and creates it.  Returns the server's representation of the rBDBackup, and an error, if there is any.
func (c *rBDBackups) Create(ctx context.Context, rBDBackup *v1.RBDBackup, opts metav1.CreateOptions) (result *v1.RBDBackup, err error) {
	result = &v1.RBDBackup{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("rbdbackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rBDBackup).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a rBDBackup and updates it. Returns the server's representation of the rBDBackup, and an error, if there is any.
func (c *rBDBackups) Update(ctx context.Context, rBDBackup *v1.RBDBackup, opts metav1.UpdateOptions) (result *v1.RBDBackup, err error) {
	result = &v1.RBDBackup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rbdbackups").
		Name(rBDBackup.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rBDBackup).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *rBDBackups) UpdateStatus(ctx context.Context, rBDBackup *v1.RBDBackup, opts metav1.UpdateOptions) (result *v1.RBDBackup, err error) {
	result = &v1.RBDBackup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rbdbackups").
		Name(rBDBackup.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rBDBackup).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the rBDBackup and deletes it. Returns an error if one occurs.
func (c *rBDBackups) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rbdbackups").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *rBDBackups) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rbdbackups").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched rBDBackup.
func (c *rBDBackups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.RBDBackup, err error) {
	result = &v1.RBDBackup{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("rbdbackups").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
